### ISSUE TITLE
fstab option results in boot error and read-only mount

### ISSUE THREAD

**Issue by ar-jan** [OpenMediaVault-Plugin-Developers/openmediavault-mergerfs#1]
I'd ticked the "fstab" option when adding a MerferFS pool, thinking this was needed to provide my own configuration. It seems that it is not actually needed though?

When I checked this option and later rebooted, I got errors and got booted into the system with root filesystem mounted read-only.

I got this from dmesg:

> systemd-fstab-generator[592]: Failed to create unit file /run/systemd/generator/-.mount, as it already exists. Duplicate entry in /etc/fstab?
> local-fs.target: Cannot add dependency job, ignoring: Unit srv-mergerfs-mypool.mount failed to load properly: File name too long.

**Comment by ryecoaaron** [comment]
You should never need the fstab checkbox.  It was provided for legacy reasons and will be going away.  And what do you mean by "your own configuration"?

The filename is hard to figure out without knowing the settings for your pool.

**Comment by ar-jan** [comment]
Well that's why I'm opening the issue ;). There was no indication the option shouldn't be used, and fstab for mounting a filesystem seemed logical. I found out the hard way which cost me quite some time to figure out.

I mean additional options like `cache.files=partial,dropcacheonclose=true`.

**Comment by ryecoaaron** [comment]
I never said it shouldn't be used or doesn't work.  I am just recommending to leave it unchecked to use systemd.

So, all I can guess without seeing your config is some option you added caused you to learn the hard way.  Checking the fstab box did not cause that.

**Comment by ar-jan** [comment]
It looks to me like it does. I also reproduced it, because I initially thought I might have made some other mistake. I check the box, apply, reboot, get mount errors. Here's the same config with the box left unchecked.

```
<mergerfs>
    <pools>
    <pool>
        <uuid>8423820d-d66e-4d98-ad88-cf8c4af0c18f</uuid>
        <enable>1</enable>
        <fstab>0</fstab>
        <name>mypool</name>
        <mntentref>b4de6106-8375-4c87-be4d-26f7646d7c18</mntentref>
        <paths>/srv/dev-disk-by-uuid-19f81656-a24c-428a-96b5-d6f4e8f80e2f/merger01:/srv/dev-disk-by-uuid-5eac5add-c11e-4c2a-9001-d2d22a089099/merger02:/srv/dev-disk-by-uuid-7773d94d-1617-4926-a0e3-623ea03ad4fa/merger03:/srv/dev-disk-by-uuid-7a7532b9-a596-4327-b398-417afc5a79a5/merger04</paths>
        <createpolicy>eplfs</createpolicy>
        <minfreespace>4</minfreespace>
        <minfreespaceunit>G</minfreespaceunit>
        <options>allow_other,use_ino,cache.files=partial,dropcacheonclose=true</options>
    </pool>
    </pools>
</mergerfs>
```

**Comment by ryecoaaron** [comment]
Well, the config looks ok.  The plugin can't control if your filesystems underneath the pool mount slow.  The reason I switched the plugin to systemd was to handle that better.  Do you have usb drives?  trapexit (author of mergerfs) suggests trying nofail in the options.  What is the output of:  sudo omv-salt deploy run mergerfs

**Comment by ar-jan** [comment]
It's regular SATA disks. They're LUKS encrypted, auto-decrypted via /etc/crypttab, but I haven't noticed any slowness.

> mynas:
> ----------
>           ID: configure_pool_dir
>     Function: file.directory
>         Name: /srv/mergerfs
>       Result: True
>      Comment: The directory /srv/mergerfs is in the correct state
>      Started: 01:24:20.652172
>     Duration: 15.479 ms
>      Changes:   
> ----------
>           ID: remove_mergerfs_mount_files_/etc/systemd/system
>     Function: module.run
>       Result: True
>      Comment: file.find: ['/etc/systemd/system/srv-mergerfs-mypool.mount']
>      Started: 01:24:20.669382
>     Duration: 19.886 ms
>      Changes:   
>               ----------
>               file.find:
>                   - /etc/systemd/system/srv-mergerfs-mypool.mount
> ----------
>           ID: configure_mergerfs_mypool
>     Function: file.managed
>         Name: /etc/systemd/system/srv-mergerfs-mypool.mount
>       Result: True
>      Comment: File /etc/systemd/system/srv-mergerfs-mypool.mount updated
>      Started: 01:24:20.689532
>     Duration: 300.778 ms
>      Changes:   
>               ----------
>               diff:
>                   New file
>               mode:
>                   0644
> ----------
>           ID: systemd-reload_mypool
>     Function: cmd.run
>         Name: systemctl daemon-reload
>       Result: True
>      Comment: Command "systemctl daemon-reload" run
>      Started: 01:24:20.997564
>     Duration: 1137.348 ms
>      Changes:   
>               ----------
>               pid:
>                   159582
>               retcode:
>                   0
>               stderr:
>               stdout:
> ----------
>           ID: enable_mypool_mergerfs
>     Function: service.enabled
>         Name: srv-mergerfs-mypool.mount
>       Result: True
>      Comment: Service srv-mergerfs-mypool.mount is already enabled, and is in the desired state
>      Started: 01:24:22.241351
>     Duration: 106.929 ms
>      Changes:   
> 
> Summary for mynas
> ------------
> Succeeded: 5 (changed=3)
> Failed:    0
> ------------
> Total states run:     5
> Total run time:   1.580 s

**Comment by ryecoaaron** [comment]
> They're LUKS encrypted, auto-decrypted via /etc/crypttab

Now the info I need comes out.  This can happen after mergerfs mounts the drives because there is nothing telling systemd to wait for LUKS to be unlock.  It starts waiting for filesystems and probably gives up before they are unlocked.  Not much I can do about that.  LUKS + filesystem + fuse filesystem is a lot of layers to get timed perfect.  I'm open to ideas on how to "fix" but this has always been an issue.

**Comment by ar-jan** [comment]
Huh. This never happens with just mounting the decrypted filesystems though? They are mounted by uuid which is only available after the LUKS volumes have been decrypted?

**Comment by ryecoaaron** [comment]
The filesystem is not encrypted.  The block device is encrypted.  The filesystem doesn't exist until the luks device is decrypted.  Only after that could mergerfs make a pool.  But mergerfs is starting its attempt to create the pool most likely before any luks devices are even attempting to unlock.  There is no dependency of LUKS for system that I know of.

**Comment by ar-jan** [comment]
>  The filesystem doesn't exist until the luks device is decrypted.

That's what I meant. Since the filesystems listed in fstab can only be mounted after the LUKS volumes have been decrypted,  and this always works correctly for the ext4 filesystems, the decryption must have already happened when fstab starts to be processed? Wouldn't the issue be with the (order of) mounting of the filesystems rather than the decryption?

**Comment by ryecoaaron** [comment]
That is not true that fstab waits for LUKS.  You can boot a system with LUKS devices and never decrypt them as long as they aren't the root filesystem.  All the plugin configures is for the mergerfs pool to wait for the filesystems.

**Comment by STPKITT** [comment]
I'd like to report that I have the same issue on a freshly installed OMV 6.x & I had also checked the "FSTAB" checkbox in the OMV GUI because I thought without it the pool wouldn't become active since I didn't even know that systemd offers it's own mounting mechanism. A short explanation in the GUI would help people tremendously!
The only left-over from my previous OMV 5.x install is the content of the data drives. They were pooled via mergerfs when I was running OMV 5.x & I never came across this issue.
My hardware didn't change at all, all data drives are SATA drives, I don't use LUKS nor any other encryption, just bog standard ext4 on all of those drives. Manually mounting the mergerfs pool takes just one or two seconds.
Regarding the statement "File name too long" from the error log what does that even mean in mergerfs' language? I mean there isn't even a filename mentioned in the fstab entry, so which file is mergerfs' refering to?
Anyway if this issue is still about slow mounts, even when it takes just one or two seconds to mount I'm sure you could manually insert a wait time somewhere.
So let me know which kind of log or so you need to figure this out.

**Comment by ryecoaaron** [comment]
File name too long is not a mergerfs concept.  That is systemd.

The plugin never explained how fstab worked previously.  So, I don't want to explain systemd either.  I have talked about adding a wiki for each plugin and putting a link in the plugin to that wiki.  I have not done that yet since I don't want to write docs.

There really isn't any log files that would help.  Systemd determines the order in which things happen.  So, while a filesystem may mount instantly, it may not come early enough and mergerfs has been waiting.  Since I don't have a system doing this, I don't know what to change.  Someone with a system will have to do some research and figure out what fixes their system.

**Comment by STPKITT** [comment]
Just one line of text next to the FSTAB checkbox would already do the trick. Write something like "Check to use fstab to mount the pool, leave unchecked for systemd to do that." Just so that the user knows what that seemingly obvious but at the same time mysterious checkbox does.

Systemd surely must create a logfile!?!
Which message actually makes you come to the conclusion that it's about slow mounts?

I also wonder why a failed mergerfs mount causes that much trouble to the overall system with logging into OMV's webinterface impossible and the system drive turning into read-only (at least that's what omv-upgrade's output told me).

I now wish I would know more or rather anything about systemd. I never had to deal with it intimately.

**Comment by ryecoaaron** [comment]
I'm not adding text to fstab because I intended on removing the option.  It was only there due to some initial problems and upgrade reasons.

Of course systemd create a logs but not really files.  I personally don't want to go through hundreds of megabytes of logs.

systemd mounts the root filesystem RO when it can't mount a filesystem.  Since the filesystems are mounted when looking at a RO filesystem and mergerfs is not, I came to the conclusion that the mount is timing out.  I think people have posted the message about a timeout as well.

**Comment by STPKITT** [comment]
That fstab checkbox is live in a non-beta release of OMV, so adding a explanation or removing that checkbox is pretty urgent. That bit of text would do no harm and relieve pressure to remove that checkbox since it seems that it's not entirely clear yet when you could remove it.

Do you think trapexit (mergerfs developer) could help or is this an issue purely when using mergerfs in OMV? If it's a general problem on several/all Linux distributions trapexit would be interested to fix it as far as I know him from online conversations.

**Comment by ryecoaaron** [comment]
I don't think it is urgent and I planned on removing it in the next release.

I am 99% sure it is not a mergerfs issue.  His documentation tells us how to use mergerfs.  Can he help?  Maybe.  But I don't have a system to provide him with any info.  So, I can't bug him about it.  I'm sure that if someone with the issue read more about systemd mounts and tried things, it could be improved.

**Comment by STPKITT** [comment]
Next release sounds good.

If I find anything substantially I may contact him, but I agree that right now it's probably too early.

**Comment by andocromn** [comment]
I'm having this same issue.  I see in the latest release the fstab option has been removed.  how can I trigger the migration from fstab to systemd?

**Comment by ryecoaaron** [comment]
sudo omv-salt deploy run fstab mergerfs
